# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 蓬莱仙岛
subtitle: 'xzyx'
description: '一起来修仙'
keywords: 内功
author: xzyx
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://xzyx.eu.org
root: /
# permalink: :year/:month/:day/:title/
permalink: :title.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)

# index_generator:
#   path: ''
#   per_page: 10
#   order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Local Search
# search:
#   path: search.xml
#   field: post
#   format: html
#   limit: 10000

# hexo-generator-searchdb
## Docs: https://github.com/theme-next/hexo-generator-searchdb
search:
  path: search.xml
  field: post
  content: true
  format: html

# Security
## Docs: https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md
encrypt: # hexo-blog-encrypt
  abstract: 有东西被加密了, 请输入密码查看.
  message: 您好, 这里需要密码.
  tags:
  - {name: 加密货币, password: dabai}
  template: <div id="hexo-blog-encrypt" data-wpm="{{hbeWrongPassMessage}}" data-whm="{{hbeWrongHashMessage}}"><div class="hbe-input-container"><input type="password" id="hbePass" placeholder="{{hbeMessage}}" /><label>{{hbeMessage}}</label><div class="bottom-line"></div></div><script id="hbeData" type="hbeData" data-hmacdigest="{{hbeHmacDigest}}">{{hbeEncryptedData}}</script></div>
  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.

# 排序
# index-generator-plus
## Docs: https://github.com/YuyingWu/hexo-generator-index-plus
index_generator_plus:
  path: '' #Root path for your blogs index page. (default = '')
  per_page: 10 #Posts displayed per page. (0 = disable pagination)
  order_by: descend #descend(default) | ascend

# 排序+隐藏(未安装)
# hexo-generator-indexed
## Docs: https://github.com/stevenjoezhang/hexo-generator-indexed
# index_generator:
#   path: ''
#   per_page: 10 #0 disables pagination
#   order_by: -date #default: date descending
#   pagination_dir: page

# hide_categories: #设置隐藏某个分类下的文章
#   - categorie1
#   - categorie2

# Markdown渲染器
# hexo-renderer-marked
## Docs: https://github.com/hexojs/hexo-renderer-marked
marked:
  gfm: true #Enables GitHub flavored markdown
  pedantic: false #Conform to obscure parts of markdown.pl as much as possible. Don't fix any of the original markdown bugs or poor behavior
  breaks: true #Enable GFM line breaks. This option requires the gfm option to be true
  smartLists: true #Use smarter list behavior than the original markdown
  smartypants: true #Use "smart" typograhic punctuation for things like quotes and dashes
  modifyAnchors: 0 #Transform the anchorIds into lower case (1) or upper case (2)
  autolink: true #Enable autolink for URLs. E.g. https://hexo.io will become <a href="https://hexo.io">https://hexo.io</a>
  sanitizeUrl: false #Remove URLs that start with javascript:, vbscript: and data:
  headerIds: true #Insert header id, e.g. <h1 id="value">text</h1>. Useful for inserting anchor link to each paragraph with a heading
  prependRoot: false #Prepend root value to (internal) image path
  external_link:
    enable: false
    exclude: []
    nofollow: false

# 隐藏posts
# hexo-hide-posts
## Docs: https://github.com/printempw/hexo-hide-posts/blob/master/README_ZH.md
hide_posts:
  filter: hide #可以改成其他你喜欢front-matter的名字
  public_generators: [tag] #指定隐藏文章仍可见的 generator，比如让所有隐藏文章在存档页面可见
  #常见的 generator 有：index, tag, category, archive, sitemap, feed, etc.
  noindex: true #为隐藏的文章添加 noindex meta 标签，阻止搜索引擎收录

# https://github.com/hexojs/hexo-generator-sitemap
sitemap:
  path: sitemap.xml #Sitemap path. (Default: sitemap.xml)
  template: #Custom template path. This file will be used to generate sitemap.xml
  rel: false #Add rel-sitemap to the site's header. (Default: false)

# https://github.com/coneycode/hexo-generator-baidu-sitemap
baidusitemap:
  path: baidusitemap.xml

# Backup
## Docs: https://github.com/coneycode/hexo-git-backup
backup:
  type: git
  theme: next
  message: Back up my blog页面底部添加又拍云(_partials/footer.swig)
  repository:
    github: git@github.com:BSDxxxx/BSDxxxx.github.io.git,backup
    coding: git@e.coding.net:gohome/BSDxxxx.git,backup

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    github: git@github.com:BSDxxxx/BSDxxxx.github.io.git,master
    coding: git@e.coding.net:gohome/BSDxxxx.git,master
    # gitee: git@gitee.com:yaohunzhanyue/BSDxxxx.git,master
  message: Site updated {{ now('YYYY-MM-DD HH:mm:ss') }}页面底部添加又拍云(_partials/footer.swig)
